// This module is included in the following assembly:
//
// *cicd/pipelines/using-tekton-chains-for-pipelines-supply-chain-security.adoc

:_content-type: CONCEPT
[id="signing-secrets-in-tekton-chains_{context}"]
= Signing secrets in {tekton-chains}

[role="_abstract"]
Cluster administrators can generate a key pair and use {tekton-chains} to sign artifacts using a Kubernetes secret. For {tekton-chains} to work, a private key and a password for encrypted keys must exist as part of the `signing-secrets` Kubernetes secret, in the `openshift-pipelines` namespace.

Currently, {tekton-chains} supports the `x509` and `cosign` signature schemes.

[NOTE]
====
Use only one of the supported signature schemes.
====

[id="chains-signing-secrets-x509_{context}"]
== Signing using x509

To use the `x509` signing scheme with {tekton-chains}, store the `x509.pem` private key of the `ed25519` or `ecdsa` type in the `signing-secrets` Kubernetes secret.

[id="chains-signing-secrets-cosign_{context}"]
== Signing using cosign

To use the `cosign` signing scheme with {tekton-chains}:

. Install link:https://docs.sigstore.dev/cosign/installation/[cosign].

. Generate the `cosign.key` and `cosign.pub` key pairs.
+
[source,terminal]
----
$ cosign generate-key-pair k8s://openshift-pipelines/signing-secrets
----
+
Cosign prompts you for a password, and creates a Kubernetes secret.

. Store the encrypted `cosign.key` private key and the `cosign.password` decryption password in the `signing-secrets` Kubernetes secret. Ensure that the private key is stored as an encrypted PEM file of the `ENCRYPTED COSIGN PRIVATE KEY` type.


[id="chains-signing-secrets-skopeo_{context}"]
== Signing using skopeo

You can generate keys using skopeo and use them in the `cosign` signing scheme with {tekton-chains}:

. Install link:https://github.com/containers/skopeo[skopeo].

. Generate a public/private key pair.
+
[source,terminal]
----
$ skopeo generate-sigstore-key --output-prefix <mykey>
----
+
Replace `<mykey>` with a key name of your choice. Skopeo prompts you for a passphrase for the private key. It then creates the key files named `<mykey>.private` and `<mykey>.pub`.
. Encode the key files using base64.
+
[source,terminal]
----
$ base64 -w 0 <mykey>.pub > b64.pub
$ base64 -w 0 <mykey>.private > b64.private
----
+
. Encode the passhprase using base64.
+
[source,terminal]
----
$ echo -n '<passphrase>' | base64 -w 0 > b64.passphrase
----
+
. Create and then edit the `signing-secrets` secret in your {pipelines-title} namespace.
+
[source,terminal]
----
$ oc create secret generic signing-secrets -n openshift-pipelines
$ oc edit secret -n openshift-pipelines signing-secrets
----
+
Add the encoded keys in the data of the secret in the following way:
+
[source,yaml]
----
apiVersion: v1
data:
  cosign.key: <Encoded <mykey>.private>
  cosign.password: <Encoded passphrase>
  cosign.pub: <Encoded <mykey>.pub>
immutable: true
kind: Secret
metadata:
  name: signing-secrets
# ...
type: Opaque
----

[id="chains-troubleshooting-signing_{context}"]
== Troubleshooting signing

If the signing secrets are already populated, you might get the following error:

[source,yaml]
----
Error from server (AlreadyExists): secrets "signing-secrets" already exists
----

To resolve the error:

. Delete the secrets:
+
[source,terminal]
----
$ oc delete secret signing-secrets -n openshift-pipelines
----

. Re-create the key pairs and store them in the secrets using your preferred signing scheme.
